name: Automated Tests for OS
on:
  push:
    branches:    
      - main            # only run on pushes to main
      - '!gh-pages'     # excludes gh-pages
  pull_request:
    branches:    
    - '**'              # matches every branch
    - '!gh-pages'       # excludes gh-pages
permissions:
  contents: read
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Setup R
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - run: Rscript -e 'print("hello")'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install numpy flake8 pytest rpy2[test]
          if [ -f requirements_tests.txt ]; then pip install -r requirements_tests.txt; fi
      - name: Check r2py
        run: |
          pytest --pyargs 'rpy2.tests'
      - name: Build package
        run: python -m build --wheel
      - name: Install Package
        run: pip install dist/*
      - name: Run tests with pytest
        run: pytest tests

